---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cns-pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis.default.svc.cluster.local
  - name: redisPassword
    value: ""
